version: '2'
services:

    storage:
        volumes:
            - ./data/development/mysql-data:/var/lib/mysql
            - ./data/development/wp-content:/var/www/html/wp-content
            - ./services/theme-builder:/usr/src/app
            - ./services/wordpress/wp-content/themes/docker:/var/www/html/wp-content/themes/docker

    wordpress:
        build:
            context: ./services/wordpress/
            dockerfile: Dockerfile.development

    pma:
        image: phpmyadmin/phpmyadmin:4.6.4-1
        links:
            - mysql:db
        ports:
            - ${PMA_PORT}:80
        environment:
            - PMA_USER=root
            - PMA_PASSWORD=root

    theme-builder:
        image: marcopeg/node:0.1
        volumes_from:
            - storage
        environment:
            - BUILD_TARGET=/var/www/html/wp-content/themes/docker
        entrypoint:
            - npm
            - start
