version: '2'
services:

    storage:
        image: busybox:1.25

    mysql:
        image: mysql:5.7
        volumes_from:
            - storage
        environment:
            - MYSQL_ROOT_PASSWORD=root

    wordpress:
        links:
            - mysql:mysql
        ports:
            - ${HUMBLE_PORT}:80
        volumes_from:
            - storage
        environment:
            - WORDPRESS_DB_PASSWORD=root

    humble:
        image: marcopeg/humble:0.1
        volumes_from:
            - storage
        volumes:
            - ./data:/data
